#!/usr/bin/env bash
#configure web-02 to be identical to web-01 
#including the custom HTTP response header (web-02)

# installs nginx on server
# update package list
apt-get -y update
# install nginx
apt-get -y install nginx
# start nginx
service nginx start
# allow incoming HTTP traffic on port 80
ufw allow 'Nginx HTTP'
# Append "Hello World!" to the default Nginx index.html file
echo "Hello World!" >> /var/www/html/index.html
# Use sed to replace the default server block with a new server block that includes a redirect rule for /redirect_me
if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
    sed -i '/listen \[::\]:80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}' /etc/nginx/sites-available/default
fi
# Create the custom 404 error page
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
# Configure Nginx to use the custom 404 error page
CONFIG_FILE="/etc/nginx/sites-available/default"
if ! grep -q "error_page 404 /404.html;" $CONFIG_FILE; then
    sed -i 's/listen \[::\]:80 default_server;/&\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}/' $CONFIG_FILE
fi
# add custom HTTP response header
if ! grep -q "add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default; then
    sudo sed -i "/^server {/a \\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default
fi
# restart nginx service
sudo systemctl restart nginx.service
