#!/usr/bin/env bash
# This script displays "To infinity and beyond"
# with a sleep 2 in between each iteration
# "I am invincible!!!" when receiving SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
