#!/usr/bin/env bash
# this script runs whoami command under
# the user passed as an argument

# validate username is provided
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# validate user existence
if id "$1" &>/dev/null; then

# Run the 'whoami' command as the specified user
  sudo -u "$1" whoami
else
  echo "User '$1' does not exist."
  exit 1
fi
