#!/usr/bin/env bash
# configure a container to run Nginx as the "nginx" user,
# listening on port 8080.

# update the package list and install Nginx
apt-get update
apt-get install -y nginx

# stop the Nginx service
service nginx stop

# validate "nginx" existence
if id "nginx" &>/dev/null; then
  echo "User 'nginx' already exists."
else
  # dreate the "nginx" user
  sudo adduser nginx
  echo "User 'nginx' has been created."
fi

# change the user and group that Nginx runs as to 'nginx'
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# change the listening port to 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# start the Nginx service
service nginx start

# clean up
apt-get clean

# display Nginx status
service nginx status

# validate Nginx is listening in on port 8080
netstat -tuln | grep 8080
